
package cl.fonasa.soa.proxy.gestioncertificado_ps;

import javax.xml.ws.WebFault;
import cl.fonasa.soa.protocolo.Fault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "gestionCertificadoFault", targetNamespace = "http://soa.fonasa.cl/gestionCertificado")
public class FaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Fault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FaultMessage(String message, Fault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FaultMessage(String message, Fault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cl.fonasa.soa.protocolo.Fault
     */
    public Fault getFaultInfo() {
        return faultInfo;
    }

}
