
package cl.fonasa.soa.proxy.gestioncertificado_ps;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "gestionCertificadoBindingQSService", targetNamespace = "http://soa.fonasa.cl/proxy/gestionCertificado_PS", wsdlLocation = "http://127.0.0.1:7101/GestionCertificadoProject/ProxyServices/gestionCertificado_PS?wsdl")
public class GestionCertificadoBindingQSService
    extends Service
{

    private final static URL GESTIONCERTIFICADOBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONCERTIFICADOBINDINGQSSERVICE_EXCEPTION;
    private final static QName GESTIONCERTIFICADOBINDINGQSSERVICE_QNAME = new QName("http://soa.fonasa.cl/proxy/gestionCertificado_PS", "gestionCertificadoBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7001/GestionCertificadoProject/ProxyServices/gestionCertificado_PS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONCERTIFICADOBINDINGQSSERVICE_WSDL_LOCATION = url;
        GESTIONCERTIFICADOBINDINGQSSERVICE_EXCEPTION = e;
    }

    public GestionCertificadoBindingQSService() {
        super(__getWsdlLocation(), GESTIONCERTIFICADOBINDINGQSSERVICE_QNAME);
    }

    public GestionCertificadoBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONCERTIFICADOBINDINGQSSERVICE_QNAME, features);
    }

    public GestionCertificadoBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONCERTIFICADOBINDINGQSSERVICE_QNAME);
    }

    public GestionCertificadoBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONCERTIFICADOBINDINGQSSERVICE_QNAME, features);
    }

    public GestionCertificadoBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionCertificadoBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestionCertificadoPortType
     */
    @WebEndpoint(name = "gestionCertificadoBindingQSPort")
    public GestionCertificadoPortType getGestionCertificadoBindingQSPort() {
        return super.getPort(new QName("http://soa.fonasa.cl/proxy/gestionCertificado_PS", "gestionCertificadoBindingQSPort"), GestionCertificadoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionCertificadoPortType
     */
    @WebEndpoint(name = "gestionCertificadoBindingQSPort")
    public GestionCertificadoPortType getGestionCertificadoBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.fonasa.cl/proxy/gestionCertificado_PS", "gestionCertificadoBindingQSPort"), GestionCertificadoPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONCERTIFICADOBINDINGQSSERVICE_EXCEPTION!= null) {
            throw GESTIONCERTIFICADOBINDINGQSSERVICE_EXCEPTION;
        }
        return GESTIONCERTIFICADOBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
